DA-2 Создание activity
PowerWarrior12/Drinkables pull request #1
Opened 2022-01-31 10:44 UTC by PowerWarrior12

2022-01-31 13:17 UTC, elza-khamdeeva requested changes

2022-01-31 13:17 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/MainActivityViewModel.kt
> +
давай в этой задаче добавим внутри методов // todo c комментарием, чтобы не коммитить пустые методы

2022-01-31 13:17 UTC, elza-khamdeeva commented on app/src/main/res/layout/activity_main.xml
>  <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
Вместо FrameLayout можно использовать FragmentContainerView
id тоже лучше назвать соответствующе, например, container

2022-01-31 13:17 UTC, elza-khamdeeva commented on app/build.gradle
>      implementation "androidx.navigation:navigation-dynamic-features-fragment:2.4.0"
зависимости выше все еще нужны в проекте?

2022-01-31 13:17 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/MainActivity.kt
> +        viewModel.navigationHolder.removeNavigator()
removeNavigator() лучше вызвать до super.onPause(), как рекомендуется в сэмпле cicerone

2022-01-31 13:17 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/MainActivityViewModel.kt
> +    private val router = cicerone.router
как насчет того, чтобы перенести это в Application?
у нас должен быть один инстанс cicerone и роутера на все приложение
другим viewModel также нужен будет доступ к этому роутеру

2022-01-31 13:17 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/MainActivity.kt
> +        if (supportFragmentManager.findFragmentById(R.id.frame_layout) == null){
не совсем очевидное условие

2022-01-31 13:18 UTC, elza-khamdeeva requested changes

2022-01-31 13:18 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/MainActivity.kt
> +private const val DETAILS_FRAGMENT = 2
зачем нам тут нужны эти константы?

2022-01-31 13:52 UTC, elza-khamdeeva requested changes

2022-01-31 13:52 UTC, elza-khamdeeva commented on app/src/main/res/navigation/main_graph.xml
> +    android:id="@+id/main_graph">
если этот файл не нужен, то нужно его удалить

2022-02-01 08:09 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/MainActivityViewModel.kt
> +
Добавил

2022-02-01 08:09 UTC, PowerWarrior12 commented on app/src/main/res/layout/activity_main.xml
>  <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
Изменил

2022-02-01 08:09 UTC, PowerWarrior12 commented on app/build.gradle
>      implementation "androidx.navigation:navigation-dynamic-features-fragment:2.4.0"
Убрал

2022-02-01 08:09 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/MainActivity.kt
> +        viewModel.navigationHolder.removeNavigator()
Поменял

2022-02-01 08:09 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/MainActivityViewModel.kt
> +    private val router = cicerone.router
Перенёс

2022-02-01 08:10 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/MainActivity.kt
> +        if (supportFragmentManager.findFragmentById(R.id.frame_layout) == null){
Перенёс в onCreate и прокомментировал

2022-02-01 08:10 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/MainActivity.kt
> +private const val DETAILS_FRAGMENT = 2
Убрал

2022-02-01 08:10 UTC, PowerWarrior12 commented on app/src/main/res/navigation/main_graph.xml
> +    android:id="@+id/main_graph">
Удалил

2022-02-01 08:25 UTC, elza-khamdeeva requested changes

2022-02-01 08:25 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/MainActivityViewModel.kt
> +    val navigationHolder = DrinksApplication.INSTANCE.navigatorHolder
давай оставим во viewModel только router

2022-02-01 08:26 UTC, elza-khamdeeva requested changes

2022-02-01 08:26 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/MainActivityViewModel.kt
> +    fun openDetailsFragment(){
тут и в методе ниже косяк с форматированием, не хватает пробела перед фигурной скобкой
сделай ctrl alt L здесь и в других классах

2022-02-01 08:54 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/MainActivityViewModel.kt
> +    val navigationHolder = DrinksApplication.INSTANCE.navigatorHolder
Сделал работу с navigationHolder напрямую через application

2022-02-01 08:54 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/MainActivityViewModel.kt
> +    fun openDetailsFragment(){
Сделал

2022-02-01 08:58 UTC, elza-khamdeeva approved these changes

2022-02-01 09:01 UTC, merged