DA-11 Добавление Bottom Sheet для характеристик напитка
PowerWarrior12/Drinkables pull request #10
Opened 2022-04-27 10:29 UTC by PowerWarrior12

2022-04-28 11:28 UTC, elza-khamdeeva requested changes

2022-04-28 11:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/data/mappers/DrinkDetailedMapper.kt
> +    private class BoilVolumeResponseToBoilVolume : EntityMapper<BoilVolumeResponse, BoilVolume> {
по логике этот класс должен называться маппер
возможно будет лучше вынести его отдельно, а не делать внутренним классом
так получится?

2022-04-28 11:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/domain/entities/Drink.kt
> +
лишний перенос

2022-04-28 11:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +        DiffUtil.ItemCallback<PropertyModel>() {
DiffCallback лучше в отдельный класс вынести

2022-04-28 11:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +                        DrinksListFragment.IS_FAVOURITE_CHANGED to drinkViewModel.isFavouriteChanged)
съехала строчка

2022-04-28 11:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +            when (resources.configuration.orientation) {
зачем здесь when если всего две ветви условия, лучше сделать if else

2022-04-28 11:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +                            DividerItemDecoration(requireContext(), DividerItemDecoration.VERTICAL)
на предыдущую строку

2022-04-28 11:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +                    !isLoading
на предыдущую строку
настрой в студии, чтобы количество символов в строке было 120, это оптимально

2022-04-28 11:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +                    !isError
и здесь

2022-04-28 11:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +                drinkDetailedContent.apply {
кажется, тут можно обойтись одним apply

2022-04-28 11:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedViewModel.kt
> +                            drink))
форматирование поправь)

2022-04-28 11:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedViewModel.kt
> +            ?: Drink()))
тут тоже

2022-04-28 11:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedViewModel.kt
> +            ?: Drink()))
нам точно нужно показывать диалог с пустым напитком?

2022-04-28 11:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/drinkProperties/PropertyDrinkDialogFragment.kt
> +        DiffUtil.ItemCallback<PropertyModel>() {
вот тут отформатированно не очень
и лучше вынести в отдельный класс, будет более читаемо

2022-04-28 11:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/drinkProperties/PropertyDrinkViewModel.kt
> +        ViewModelProvider.NewInstanceFactory() {
на строчку выше

2022-04-28 11:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListFragment.kt
> +            SearchView.OnQueryTextListener {
на строчку выше должно поместиться
если нет, то перенос строки должен быть после круглой скобки

2022-04-28 11:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/navigation/DialogScreen.kt
> +// DialogScreen.kt
неинформативный комментарий можно убрать)

2022-04-28 11:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/utils/customAdapter/CompositeDelegateAdapter.kt
> +            ?.onBindViewHolder(holder, currentList, position)
на строку выше

2022-04-28 11:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/utils/customAdapter/CompositeDelegateAdapter.kt
> +    itemCallback: DiffUtil.ItemCallback<T>,
для адаптер делегатов есть вот такая библиотечка, очень удобная, не нужно писать бойлерплейт код
посмотри, может быть понравится
https://github.com/sockeqwe/AdapterDelegates

2022-05-03 17:12 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/data/mappers/DrinkDetailedMapper.kt
> +    private class BoilVolumeResponseToBoilVolume : EntityMapper<BoilVolumeResponse, BoilVolume> {
получится, сделал

2022-05-03 17:13 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/domain/entities/Drink.kt
> +
убрал

2022-05-04 06:53 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/utils/customAdapter/CompositeDelegateAdapter.kt
> +    itemCallback: DiffUtil.ItemCallback<T>,
Заменил

2022-05-04 06:53 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +        DiffUtil.ItemCallback<PropertyModel>() {
Вынес

2022-05-04 07:17 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +            when (resources.configuration.orientation) {
Сделал

2022-05-04 07:18 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +                            DividerItemDecoration(requireContext(), DividerItemDecoration.VERTICAL)
Перенёс

2022-05-04 07:20 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +                    !isLoading
Перенёс и настроил

2022-05-04 07:21 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +                    !isError
Перенёс

2022-05-04 07:50 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +                drinkDetailedContent.apply {
Кажется да, сделал

2022-05-04 07:51 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedViewModel.kt
> +                            drink))
поправил

2022-05-04 07:54 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedViewModel.kt
> +            ?: Drink()))
Поправил, пустой напиток долой

2022-05-04 08:03 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/drinkProperties/PropertyDrinkDialogFragment.kt
> +        DiffUtil.ItemCallback<PropertyModel>() {
Если про DiffCollback, то вынес

2022-05-04 08:04 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/drinkProperties/PropertyDrinkViewModel.kt
> +        ViewModelProvider.NewInstanceFactory() {
Перенёс

2022-05-04 08:06 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListFragment.kt
> +            SearchView.OnQueryTextListener {
Сделал

2022-05-04 08:08 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/navigation/DialogScreen.kt
> +// DialogScreen.kt
Убрал

2022-05-04 08:09 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/utils/customAdapter/CompositeDelegateAdapter.kt
> +            ?.onBindViewHolder(holder, currentList, position)
Файла больше нет, так что никак(

2022-05-04 08:11 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +                        DrinksListFragment.IS_FAVOURITE_CHANGED to drinkViewModel.isFavouriteChanged)
поправил

2022-05-09 16:14 UTC, merged