DA-3 Создание экрана для списка напитков
PowerWarrior12/Drinkables pull request #2
Opened 2022-02-03 08:16 UTC by PowerWarrior12

…list of drinks from remote source, create progress bar, error visualisation and ability to reload if occurred error

2022-02-03 09:02 UTC, elza-khamdeeva requested changes

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/Configurations.kt
> +const val url = "https://api.punkapi.com/v2/"
константы должны быть написаны капсом через нижнее подчеркивание
давай назовем эту константу BASE_URL ?

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/data/api/RetrofitService.kt
> +            level = HttpLoggingInterceptor.Level.BODY// чтобы в логах отображалось
перед комментом пробела не хватает)

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/data/repositories/DrinkRepository.kt
> +const val ERROR_MESSAGE = "Error of loading"
кажется, эту константу можно сделать приватной

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/data/repositories/DrinkRepository.kt
> +    private val service: DrinksApi,
давай это поле назовем по-другому?
например, drinksApi или drinksRestApi
кажется, service не очень подходящее и слишком обширное название

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/data/repositories/IDrinksRepository.kt
> +interface IDrinksRepository {
не критично, но лучше, если интерфейсы мы называть без префикса I в начале.
например,
интерфейс - DrinksRepository
имплементация - DrinksRepositoryImpl

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/Dagger.kt
> +interface AppComponent {
давай все классы разнесем по разным файлам?

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/DrinksApplication.kt
>      val navigatorHolder get() = cicerone.getNavigatorHolder()
кажется, самое время занести cicerone в appModule
и предоставлять router вьюмоделям через зависимости

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinkViewHolder.kt
> +        fun run()
лучше назвать интерфейс c постфиксом Listener, например, DrinksListener или DrinkViewListener
а внутри будет метод onHeartButtonClick()

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksAdapter.kt
> +            return oldItem == newItem
здесь можно по айдишникам сравнивать 
oldItem.is == newItem.id
если разные id, значит и элементы разные

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksAdapter.kt
> +            return oldItem == newItem
и я бы вынесла в отдельный файл этот класс

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksAdapter.kt
> +        fun newInstance(
на мой взгляд, newInstance здесь излишне заводить

давай уберем companion object, а listener будем передавать в конструкторе

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListFragment.kt
> +    private lateinit var drinksRecyclerView: RecyclerView
lateinit лучше не использовать, кроме как для инджекта полей с помощью даггера
так как можно получить исключение, если что-то не инициализировалось

используй by lazy
или инициализируй сразу, например,
private var adapter: Adapter? = null

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListFragment.kt
> +        drinksRecyclerView = view.findViewById(R.id.drinks_recycler_view)
затащим view binding в проект?

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListFragment.kt
> +                TODO("Create logic for click on heart button")
вот такие тудушки лучше не оставлять, при клике крашнется приложение

пиши вот так, например,
// todo добавить обработку нажатия

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListFragment.kt
> +        drinksViewModel.getDrinks()
можно это сделать в блоке init у viewModel

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListFragment.kt
> +        drinksViewModel.getDrinks()
проверь только, чтобы работало как надо

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListFragment.kt
> +        // Inflate the layout for this fragment
этот коммент можно убрать. и так понятно

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListFragment.kt
> +    private fun initialization(view: View) {
как правило, методы называются глаголами
давай сделаем так:
1. перепишем на viewBinding, это поможет избавиться от методов findViewById и от параметра view в этом методе
2. переименуем метод на initViews()

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListFragment.kt
> +    private fun initialization(view: View) {
3. перенесем вызов этого метода в onViewCreated

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListFragment.kt
> +        @JvmStatic
зачем нам тут эта аннотация?

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListFragment.kt
> +            DrinksListFragment()
по-моему в одну строчку уместится)

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListViewModel.kt
> +    private val scope = CoroutineScope(job + Dispatchers.IO)
внутри viewModel можно использовать viewModelScope
его не нужно будет закрывать, это произойдет автоматически после уничтожения viewModel

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListFragment.kt
> +                    false -> errorButton.visibility = View.GONE
можно использовать стандартный extension isVisible
таким образом, метод будет выглядеть так:

dinksViewModel.error.observe(viewLifecycleOwner) { isError ->
    errorButton.isVisible = isError
}

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListViewModel.kt
> +    val error = MutableLiveData<Boolean>(false)
давай эти поля переименуем в более понятные
drinksListLiveData, loadingLiveData  и тд
или хотя бы
loadingLive, drinksListLive  и тд

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListViewModel.kt
> +            when (val result = loadDrinksInteractor.run()) {
переменная result тут зачем?

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListViewModel.kt
> +                    drinksList.postValue(result.data!!)
а если data будет null?

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListViewModel.kt
> +                    drinksList.postValue(mutableListOf())
нужно ли постить пустой список?
может просто скрывть recyclerView во фрагменте, если пришла ошибка?
или выводить ошибку поверх на весь экран

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/Screens.kt
> +    object DrinksListFragmentInstance : FragmentScreen {
а зачем еще один object внутри?

можно написать метод
fun DrinksListFragment() = FragmentScreen {

}

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/res/layout/drink_item.xml
> +    xmlns:app="http://schemas.android.com/apk/res-auto"
LinearLayout или FrameLayout здесь не обойдемся?

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/res/layout/fragment_drinks_list.xml
> +    </androidx.recyclerview.widget.RecyclerView>
убери эту строчку, а тэг закрой выше
так, как у тебя сделано в ImageButton

2022-02-03 09:02 UTC, elza-khamdeeva commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
это, кажется, можно удалить

2022-02-03 10:08 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/Configurations.kt
> +const val url = "https://api.punkapi.com/v2/"
Переименовал

2022-02-03 10:09 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/data/api/RetrofitService.kt
> +            level = HttpLoggingInterceptor.Level.BODY// чтобы в логах отображалось
Добавил

2022-02-03 10:13 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/data/repositories/DrinkRepository.kt
> +const val ERROR_MESSAGE = "Error of loading"
Сделал

2022-02-03 10:14 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/data/repositories/DrinkRepository.kt
> +    private val service: DrinksApi,
Переименовал

2022-02-03 10:28 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/data/repositories/IDrinksRepository.kt
> +interface IDrinksRepository {
Переименовал

2022-02-03 10:38 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/Dagger.kt
> +interface AppComponent {
Разнёс

2022-02-03 11:17 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/DrinksApplication.kt
>      val navigatorHolder get() = cicerone.getNavigatorHolder()
Занёс

2022-02-03 11:29 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinkViewHolder.kt
> +        fun run()
Переименовал

2022-02-03 12:28 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksAdapter.kt
> +            return oldItem == newItem
Исправил

2022-02-03 13:02 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksAdapter.kt
> +        fun newInstance(
Исправил

2022-02-04 08:40 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListFragment.kt
> +    private lateinit var drinksRecyclerView: RecyclerView
Исправил

2022-02-04 08:40 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListFragment.kt
> +        drinksRecyclerView = view.findViewById(R.id.drinks_recycler_view)
Затащил

2022-02-04 08:41 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListFragment.kt
> +                TODO("Create logic for click on heart button")
Убрал

2022-02-04 08:41 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListFragment.kt
> +        // Inflate the layout for this fragment
Убрал

2022-02-04 08:43 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListFragment.kt
> +    private fun initialization(view: View) {
Переделал

2022-02-04 08:43 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListFragment.kt
> +        @JvmStatic
Убрал

2022-02-04 08:43 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListFragment.kt
> +            DrinksListFragment()
Сделал в одной строке

2022-02-04 08:55 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListViewModel.kt
> +    private val scope = CoroutineScope(job + Dispatchers.IO)
Поменял

2022-02-04 09:50 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListFragment.kt
> +                    false -> errorButton.visibility = View.GONE
Поменял

2022-02-04 09:55 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListViewModel.kt
> +    val error = MutableLiveData<Boolean>(false)
Переименовал

2022-02-04 10:38 UTC, PowerWarrior12 commented on app/src/main/res/layout/fragment_drinks_list.xml
> +    </androidx.recyclerview.widget.RecyclerView>
Исправил

2022-02-04 10:39 UTC, PowerWarrior12 commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
Удалил

2022-02-04 11:28 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/Screens.kt
> +    object DrinksListFragmentInstance : FragmentScreen {
Поменял

2022-02-04 16:53 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListFragment.kt
> +        drinksViewModel.getDrinks()
Переместил

2022-02-04 17:51 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListViewModel.kt
> +                    drinksList.postValue(result.data!!)
Добавил проверку на null :
result.data ?: mutableListOf()

2022-02-04 17:52 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListViewModel.kt
> +                    drinksList.postValue(mutableListOf())
Убрал пост пустого списка

2022-02-05 05:19 UTC, PowerWarrior12 commented on app/src/main/res/layout/drink_item.xml
> +    xmlns:app="http://schemas.android.com/apk/res-auto"
Поменял на LinearLayout

2022-02-05 05:43 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/DrinksList/DrinksListViewModel.kt
> +            when (val result = loadDrinksInteractor.run()) {
Она ниже используется, что бы вытащить данные

2022-02-07 11:33 UTC, elza-khamdeeva requested changes

2022-02-07 11:33 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/data/mappers/IEntityMapper.kt
> +interface IEntityMapper<F, T> {
давай здесь тоже без I  в начале

2022-02-07 11:33 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListFragment.kt
> +        DrinksAdapter(object : DrinkViewHolder.DrinkViewListener {
на предыдущую строку можно перенести

2022-02-07 11:33 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListFragment.kt
> +
лишний перенос

2022-02-07 11:33 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListFragment.kt
> +        return drinksListBinding.root
можно через = сделать
= drinksListBinding.root

2022-02-07 11:33 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListFragment.kt
> +        drinksViewModel.drinksListLiveData.observe(
давай методы observe вынесем в отдельный метод
назовем его, например, observeData

2022-02-07 11:33 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListFragment.kt
> +                    false -> drinksListBinding.progressBar.visibility = View.GONE
можно проще
drinksViewModel.loadingLivaData.observe(viewLifecycleOwner) { isLoading ->
    drinksListBinding.progressBar.isVisible = isLoading 
}

2022-02-07 11:33 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListFragment.kt
> +    private val drinksListBinding by lazy {
назови просто binding

2022-02-07 11:33 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListViewModel.kt
> +            when (val result = loadDrinksInteractor.run()) {
не вижу, где у тебя еще result используется

2022-02-07 11:41 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/data/mappers/IEntityMapper.kt
> +interface IEntityMapper<F, T> {
Переименовал

2022-02-07 11:43 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListFragment.kt
> +        DrinksAdapter(object : DrinkViewHolder.DrinkViewListener {
Перенёс

2022-02-07 11:43 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListFragment.kt
> +
Убрал

2022-02-07 11:44 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListFragment.kt
> +        return drinksListBinding.root
Сделал через =

2022-02-07 11:45 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListFragment.kt
> +        drinksViewModel.drinksListLiveData.observe(
Вынес в отдельный метод

2022-02-07 11:47 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListFragment.kt
> +                    false -> drinksListBinding.progressBar.visibility = View.GONE
Заменил

2022-02-07 11:49 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListFragment.kt
> +    private val drinksListBinding by lazy {
Переименовал

2022-02-07 11:54 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListViewModel.kt
> +            when (val result = loadDrinksInteractor.run()) {
`            when (val result = loadDrinksInteractor.run()) {
                is Result.Success -> {
                    drinksListLiveData.postValue(result.data ?: mutableListOf())
                }`

2022-02-07 11:55 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListViewModel.kt
> +            when (val result = loadDrinksInteractor.run()) {
в drinksListLiveData.postValue

2022-02-07 12:41 UTC, elza-khamdeeva requested changes

2022-02-07 12:41 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListViewModel.kt
> +            when (val result = loadDrinksInteractor.run()) {
давай тогда для читаемости вынесем отдельно переменную
перед when

2022-02-07 12:41 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListFragment.kt
> +
давай уберем лишние переносы строк
50 и 52 строчки

2022-02-07 12:48 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListViewModel.kt
> +            when (val result = loadDrinksInteractor.run()) {
Вынес

2022-02-07 12:50 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListFragment.kt
> +
Убрал

2022-02-07 12:54 UTC, elza-khamdeeva approved these changes

2022-02-08 04:49 UTC, merged