DA-4 Создание экрана для детальной информации
PowerWarrior12/Drinkables pull request #3
Opened 2022-02-08 09:55 UTC by PowerWarrior12

2022-02-08 13:55 UTC, elza-khamdeeva requested changes

2022-02-08 13:55 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/data/api/DrinksApi.kt
> +    ): Response<MutableList<DrinkDetailedApiResponse>>
смотри, вот тут в названии класса api кажется излишним
давай попроще напишем
DrinkResponse или DrinkDetailedResponse

в запросе выше тоже оставь DrinksResponse

2022-02-08 13:55 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/data/api/entities/DrinkDetailedApiResponse.kt
> +    val image_url: String
название поле должно быть camelCase
imageUrl

Добавь над каждым полем аннотацию @SerializedName("image_url")

2022-02-08 13:55 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/domain/entities/DrinkViewEntity.kt
>  data class DrinkViewEntity(
как правило, класс называют entity, если он помещается в бд
для остальных ответов достаточно просто Drink
и еще слово View в названии класса тоже смущает, обычно так вьюшки называют, а у нас моделька

2022-02-08 13:55 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/Screens.kt
> +    fun drinkDetailedFragment(id: Int) = FragmentScreen {
давай переименуем в drinkId, чтобы было понятно какой именно айдишник от нас требуется

2022-02-08 13:55 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/di/AppComponent.kt
> +    fun inject(fragment: DrinksListViewModel)
сейчас у тебя зависимости для экранов лежат в AppModule
по-хорошему, это стоит вынести в отдельный модуль для твоих экранов
но так как проект у нас маленький, пока можно оставить
может потом отрефакторим

2022-02-08 13:55 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +                binding.apply {
это в отельный метод давай вынесем

2022-02-08 13:55 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +            viewLifecycleOwner, { bitmap ->
давай сделаем так:
drinkViewModel.imageLiveData.observe(viewLifecycleOwner) {

}
вынесем лямбду за скобки, в других местах так же

2022-02-08 13:55 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +                arguments = Bundle().apply {
можно использовать функцию bundleOf()

arguments = bundleOf(DRINK_ID to drinkId)

2022-02-08 13:55 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedViewModel.kt
> +        @Assisted(DRINK_ID) private val id: Int
огонь

2022-02-08 13:55 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedViewModel.kt
> +            fun create(@Assisted(DRINK_ID) id: Int): DrinkDetailedViewModel.DrinkDetailedViewModelFactory
если в конструкторе один параметр такого типа, можно без аннотации @Assisted(DRINK_ID) сделать
и выше DRINK_ID тоже можно убрать

если параметров больше, то тогда аннотации с ключами нужны

2022-02-08 13:55 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedViewModel.kt
> +            fun create(@Assisted(DRINK_ID) id: Int): DrinkDetailedViewModel.DrinkDetailedViewModelFactory
опционально, не обязательно исправлять

2022-02-08 13:55 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListViewModel.kt
> +    lateinit var router: Router
а в конструктор viewModel получится затащить роутер?

2022-02-08 13:55 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListViewModel.kt
> +        DrinksApplication.INSTANCE.appComponent.inject(this)
вот от этого нужно как-то избавиться

2022-02-08 13:55 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/utils/ImageLoader.kt
> +    fun loadImageWithUrl(url: String): Bitmap {
давай попробуем использовать библиотеку Glide?

2022-02-08 13:55 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinkViewHolder.kt
> +                    binding.viewModel?.drinkViewEntity?.id ?: DEFAULT_DRINK_ID
DrinkItemViewModel здесь это что такое?

2022-02-08 14:03 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/data/api/DrinksApi.kt
> +    ): Response<MutableList<DrinkDetailedApiResponse>>
Переименовал

2022-02-08 14:05 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/data/api/entities/DrinkDetailedApiResponse.kt
> +    val image_url: String
Добавил

2022-02-08 14:06 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/domain/entities/DrinkViewEntity.kt
>  data class DrinkViewEntity(
Переименовал

2022-02-08 14:07 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/Screens.kt
> +    fun drinkDetailedFragment(id: Int) = FragmentScreen {
Переименовал

2022-02-08 14:10 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/di/AppComponent.kt
> +    fun inject(fragment: DrinksListViewModel)
Вынес

2022-02-08 14:14 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +            viewLifecycleOwner, { bitmap ->
Исправил

2022-02-08 14:28 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +                binding.apply {
Вынес

2022-02-08 14:37 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +                arguments = Bundle().apply {
Заменил

2022-02-08 14:38 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedViewModel.kt
> +            fun create(@Assisted(DRINK_ID) id: Int): DrinkDetailedViewModel.DrinkDetailedViewModelFactory
Исправил

2022-02-08 14:39 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedViewModel.kt
> +        @Assisted(DRINK_ID) private val id: Int
Не понял

2022-02-08 14:41 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListViewModel.kt
> +    lateinit var router: Router
Затащил

2022-02-08 14:41 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListViewModel.kt
> +        DrinksApplication.INSTANCE.appComponent.inject(this)
Избавился

2022-02-08 14:46 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinkViewHolder.kt
> +                    binding.viewModel?.drinkViewEntity?.id ?: DEFAULT_DRINK_ID
Вью модель для data binding

2022-02-08 17:02 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/utils/ImageLoader.kt
> +    fun loadImageWithUrl(url: String): Bitmap {
Использовал

2022-02-09 10:55 UTC, elza-khamdeeva requested changes
https://github.com/androidbroadcast/ViewBindingPropertyDelegate

Посмотри вот эту библиотеку для viewBinding, c ней удобнее
попробуй внедрить
позволит избавиться от лишнего кода
и от тегов layout в верстке

2022-02-09 10:55 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/di/ScreenAppModule.kt
> +class ScreenAppModule {
Почему назвал ScreenApp?
Кажется, NavigationModule больше подходит, так как внутри провайдятся зависимости для навигации

2022-02-09 10:55 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +            fillDrinkData(drink)
можно еще больше упростить запись
drinkViewModel.drinkDetailedLiveData.observe(viewLifecycleOwner, ::fillDrinkData)

2022-02-09 10:55 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +        Glide
давай вынесем этот экстеншн в отдельный файл
таким образом, его можно будет использовать и в других фрагментах

2022-02-09 10:55 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedViewModel.kt
>      private val id: Int
тоже лучше drinkId назвать

2022-02-09 10:55 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedViewModel.kt
> +                    drinkDetailedLiveData.postValue(result.data ?: Drink())
а нам точно нужно постить Drink() с дефолтными полями, если даты нет?
кажется, лучше сначала сделать проверку и постить гарантированно адекватный ответ

2022-02-09 10:55 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedViewModel.kt
> +        @Assisted private val id: Int
сделай название drinkId

2022-02-09 10:55 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinkItemCallback.kt
> +        newItem: Drink
давай параметры в одну строчку сделаем, как в методе выше

2022-02-09 10:55 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListFragment.kt
> +            drinksAdapter.submitList(list)
drinksViewModel.drinksListLiveData.observe(viewLifecycleOwner, ::submitList)

2022-02-10 06:43 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/di/ScreenAppModule.kt
> +class ScreenAppModule {
Переименовал

2022-02-10 06:48 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +            fillDrinkData(drink)
Упростил

2022-02-10 06:54 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +        Glide
Перенёс

2022-02-10 06:56 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedViewModel.kt
>      private val id: Int
Переименовал

2022-02-10 07:01 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedViewModel.kt
> +                    drinkDetailedLiveData.postValue(result.data ?: Drink())
Сделал

2022-02-10 07:01 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedViewModel.kt
> +        @Assisted private val id: Int
Переименовал

2022-02-10 07:02 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinkItemCallback.kt
> +        newItem: Drink
Сделал

2022-02-10 07:11 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListFragment.kt
> +            drinksAdapter.submitList(list)
Поменял

2022-02-10 08:38 UTC, elza-khamdeeva requested changes

2022-02-10 08:38 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedViewModel.kt
> +                        drinkDetailedLiveData.postValue(it)
result.data.let(drinkDetailedLiveData::postValue)
или добавь именованный параметр вместо it

2022-02-10 08:38 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinkViewHolder.kt
> +    RecyclerView.ViewHolder(view) {
на предыдущую строку лучше перенести

2022-02-10 08:38 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinkViewHolder.kt
> +            drinkTitleText.text = drink?.title
из-за того, что drink nullabale получается много сейф коллов
давай сделаем проверку и избавимся от низ
и от DEFAULT_DRINK_ID

2022-02-10 08:39 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedViewModel.kt
> +                        drinkDetailedLiveData.postValue(it)
исправил

2022-02-10 08:39 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinkViewHolder.kt
> +    RecyclerView.ViewHolder(view) {
Перенёс

2022-02-10 08:42 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinkViewHolder.kt
> +            drinkTitleText.text = drink?.title
Внёс проверку убрал DEFAULT_DRINK_ID

2022-02-10 08:52 UTC, elza-khamdeeva requested changes

2022-02-10 08:52 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinkViewHolder.kt
> +                        drink.id
ну вот тут лучше не переносить строку, в предыдущей уместится и лаконичнее смотреться будет
27 строка аналогично

2022-02-10 08:55 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinkViewHolder.kt
> +                        drink.id
Убрал переносы

2022-02-10 08:56 UTC, elza-khamdeeva approved these changes

2022-02-10 09:00 UTC, merged