Add favorite drinks
PowerWarrior12/Drinkables pull request #4
Opened 2022-02-14 11:26 UTC by PowerWarrior12

2022-02-14 13:28 UTC, elza-khamdeeva requested changes

2022-02-14 13:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/data/repositories/DrinksRepositoryImpl.kt
> +        return false
return drinkDB.drinkDao().getFavouriteDrink(drinkId) != null 

?

2022-02-14 13:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/data/repositories/FavouriteDrinksRepository.kt
> +    suspend fun getFavouritesDrinksId() : List<Int>
как насчет такого варианта? getFavouritesDrinkIds()

2022-02-14 13:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/domain/entities/Drink.kt
> +    var favourites: Boolean = false,
лучше оставить поля неизменяемыми val
а чтобы поменять значение использовать функцию copy
а в списке реплейсить объект

2022-02-14 13:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/domain/interactors/LoadDrinkDetailedInteractor.kt
> +    suspend fun run(id: Int, scope: CoroutineScope): Result<Drink> {
зачем здесь CoroutineScope добавился
и есть неиспользуемые импорты в классе

2022-02-14 13:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedViewModel.kt
> +                        drinkDetailedLiveData.postValue(updateDrinkFavouriteInteractor.run(drink))
updateDrinkFavouriteInteractor.run(drink) - давай вынесем в отдельную переменную

2022-02-14 13:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinkViewHolder.kt
> +                heartButton.apply {
apply здесь лишний

2022-02-14 13:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinkViewHolder.kt
> +                false -> setBackgroundResource(R.drawable.ic_heart)
если всего 2 значения true и false, то лучше использовать конструкцию if/else

2022-02-14 13:28 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListViewModel.kt
> +                        drinksListLiveData.postValue(updateDrinksFavouritesInteractor.run(drinks))
updateDrinksFavouritesInteractor.run(drinks) вынеси в переменную

2022-02-16 08:59 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/data/repositories/DrinksRepositoryImpl.kt
> +        return false
Поменял

2022-02-16 09:01 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/data/repositories/FavouriteDrinksRepository.kt
> +    suspend fun getFavouritesDrinksId() : List<Int>
Переименовал

2022-02-16 09:51 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/domain/entities/Drink.kt
> +    var favourites: Boolean = false,
Сделал

2022-02-16 09:52 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/domain/interactors/LoadDrinkDetailedInteractor.kt
> +    suspend fun run(id: Int, scope: CoroutineScope): Result<Drink> {
Убрал

2022-02-16 10:07 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedViewModel.kt
> +                        drinkDetailedLiveData.postValue(updateDrinkFavouriteInteractor.run(drink))
Вынес

2022-02-16 10:31 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinkViewHolder.kt
> +                heartButton.apply {
Убрал

2022-02-16 10:33 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinkViewHolder.kt
> +                false -> setBackgroundResource(R.drawable.ic_heart)
Поменял

2022-02-16 10:36 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinksListViewModel.kt
> +                        drinksListLiveData.postValue(updateDrinksFavouritesInteractor.run(drinks))
вынес

2022-02-17 09:00 UTC, elza-khamdeeva requested changes

2022-02-17 09:00 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/data/repositories/DrinksRepositoryImpl.kt
> +    override suspend fun getFavouritesDrinkids(): List<Int> {
getFavouriteDrinkIds()

давай так
Ids с большой буквы

2022-02-17 09:00 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/domain/interactors/UpdateDrinksFavouritesInteractor.kt
> +            drinks[drinks.indexOf(drink)] = drink.copy(favourites = favourites.contains(drink.id))
давай drinks.indexOf(drink) вынесем в отдельную переменную для улучшения читаемости кода

2022-02-17 09:50 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/data/repositories/DrinksRepositoryImpl.kt
> +    override suspend fun getFavouritesDrinkids(): List<Int> {
Переименовал

2022-02-17 09:56 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/domain/interactors/UpdateDrinksFavouritesInteractor.kt
> +            drinks[drinks.indexOf(drink)] = drink.copy(favourites = favourites.contains(drink.id))
Вынес

2022-02-18 12:34 UTC, elza-khamdeeva approved these changes

2022-02-18 12:50 UTC, merged