DA-7 Добавление анимаций
PowerWarrior12/Drinkables pull request #6
Opened 2022-03-14 15:13 UTC by PowerWarrior12

2022-03-15 14:29 UTC, elza-khamdeeva requested changes

2022-03-15 14:29 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinkViewHolder.kt
> +    fun bind(drink_: Drink, callback: DrinkViewListener) {
зачем название с нижним подчеркиванием?
назови drink
а к полю класса с таким же названием обращайся через this

2022-03-15 14:29 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/utils/views/ViewsAnimations.kt
> +fun View.startJellyAnimation(duration: Long, scale_: Float) {
scale давай тоже без нижнего подчеркивания

2022-03-15 14:29 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/utils/views/ViewsAnimations.kt
> +    setAnimator.start()
чтобы не обращаться к setAnimator 4 раза подряд, можно применить
with(setAnimator) {
 ...
}

2022-03-15 14:51 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksList/DrinkViewHolder.kt
> +    fun bind(drink_: Drink, callback: DrinkViewListener) {
Переименовал

2022-03-15 14:52 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/utils/views/ViewsAnimations.kt
> +fun View.startJellyAnimation(duration: Long, scale_: Float) {
Переименовал

2022-03-15 15:01 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/utils/views/ViewsAnimations.kt
> +    setAnimator.start()
Применил

2022-03-17 07:32 UTC, elza-khamdeeva approved these changes

2022-03-22 07:20 UTC, merged