DA-8 Доработки
PowerWarrior12/Drinkables pull request #7
Opened 2022-03-22 12:44 UTC by PowerWarrior12

…s to image upload and upload error. Adapting the screen, changing the text, font.

2022-03-22 13:54 UTC, elza-khamdeeva requested changes

2022-03-22 13:54 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +        drinkViewModel.errorDrinkLiveData.observe(viewLifecycleOwner){ isError ->
отформатировать строчку надо

2022-03-22 13:54 UTC, elza-khamdeeva commented on app/src/main/res/layout-land/fragment_drink_detailed.xml
> +        android:layout_marginBottom="16dp"
можно указать одну строчку android:layout_margin="16dp"

2022-03-22 13:54 UTC, elza-khamdeeva commented on app/src/main/res/layout-land/fragment_drink_detailed.xml
> +        android:layout_marginBottom="16dp"
то же самое

2022-03-22 13:54 UTC, elza-khamdeeva commented on app/src/main/res/layout-land/fragment_drink_detailed.xml
> +        android:layout_marginBottom="16dp"
и здесь

2022-03-22 14:15 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinkDetailed/DrinkDetailedFragment.kt
> +        drinkViewModel.errorDrinkLiveData.observe(viewLifecycleOwner){ isError ->
Исправил

2022-03-22 14:15 UTC, PowerWarrior12 commented on app/src/main/res/layout-land/fragment_drink_detailed.xml
> +        android:layout_marginBottom="16dp"
Исправил

2022-03-22 14:16 UTC, PowerWarrior12 commented on app/src/main/res/layout-land/fragment_drink_detailed.xml
> +        android:layout_marginBottom="16dp"
Исправил

2022-03-22 14:18 UTC, PowerWarrior12 commented on app/src/main/res/layout-land/fragment_drink_detailed.xml
> +        android:layout_marginBottom="16dp"
Исправил

2022-03-23 07:22 UTC, elza-khamdeeva approved these changes

2022-03-24 07:03 UTC, merged