Feature/da 9 Создание toolbar и Bottom Navigation View
PowerWarrior12/Drinkables pull request #8
Opened 2022-04-04 08:39 UTC by PowerWarrior12

2022-04-04 13:12 UTC, elza-khamdeeva requested changes

2022-04-04 13:12 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksFavorite/FavouritesAdapter.kt
> +                .inflate(R.layout.favourite_drink_item, parent, false)
по-моему на предыдущей строке уместится

2022-04-04 13:12 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksFavorite/FavouritesAdapter.kt
> +            it.copy()
давай добавим именованный параметр, вместо it

2022-04-04 13:12 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksFavorite/FavouritesListFragment.kt
> +                favouritesViewModel.openDetailedWindow(id)
Смотри, у нас viewModel управляет фрагментом, а не наоборот 
Это должно соблюдаться и на уровне именований методов тоже
Поэтому здесь нужно назвать метод onCurrentDrinkClick(), а не говорить вьюмодели открыть деталку
Вьюмодель должна сама определять, что нужно сделать по клику на напиток

2022-04-04 13:12 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/drinksFavorite/FavouritesListFragment.kt
> +            favouritesAdapter.submitList(it.toMutableList())
Давай добавим именованный параметр вместо it

2022-04-04 13:12 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/mainActivity/MainActivity.kt
> +                R.id.navigation_favourites -> viewModel.openFavouritesFragment()
вот здесь по поводу названий методов то же самое, что в комментарии выше
onCatalogSelected
onFavouritesSelected

2022-04-04 13:12 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/mainActivity/MainActivity.kt
> +        return super.onCreateView(name, context, attrs)
по-моему этот метод можно удалить)

2022-04-04 13:12 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/utils/views/ViewsNavigation.kt
> +import android.view.MenuItem
я бы этот файл назвала BottomNavigationViewExtensions.kt

2022-04-05 13:24 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksFavorite/FavouritesAdapter.kt
> +                .inflate(R.layout.favourite_drink_item, parent, false)
уместил

2022-04-05 13:24 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksFavorite/FavouritesAdapter.kt
> +            it.copy()
добавил

2022-04-05 13:26 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksFavorite/FavouritesListFragment.kt
> +                favouritesViewModel.openDetailedWindow(id)
Сделал

2022-04-05 13:27 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/drinksFavorite/FavouritesListFragment.kt
> +            favouritesAdapter.submitList(it.toMutableList())
Добавил

2022-04-05 13:30 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/mainActivity/MainActivity.kt
> +                R.id.navigation_favourites -> viewModel.openFavouritesFragment()
Поменял

2022-04-05 13:30 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/presentation/mainActivity/MainActivity.kt
> +        return super.onCreateView(name, context, attrs)
удалил

2022-04-05 13:31 UTC, PowerWarrior12 commented on app/src/main/java/com/example/drinkables/utils/views/ViewsNavigation.kt
> +import android.view.MenuItem
Переименовал

2022-04-07 07:14 UTC, elza-khamdeeva commented on app/src/main/java/com/example/drinkables/presentation/mainActivity/MainActivity.kt
> +                R.id.navigation_catalog -> viewModel.openFirstFragment()
вот здесь разве не  onCatalogSelected() должно быть?

2022-04-11 09:58 UTC, elza-khamdeeva approved these changes

2022-04-11 12:54 UTC, merged